#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use Illuminate\Database\{
	Capsule\Manager as CapsuleManager,
	Migrations\DatabaseMigrationRepository,
	Migrations\Migrator,
};
use Illuminate\Filesystem\Filesystem;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();
$dotenv->required([
	'DB_DRIVER',
	'DB_HOST',
	'DB_PORT',
	'DB_NAME',
	'DB_PASS',
	'DB_USER',
])->notEmpty();

$capsule = new CapsuleManager();

$capsule->addConnection([
	'driver' => $_ENV['DB_DRIVER'],
	'host' => $_ENV['DB_HOST'],
	'port' => $_ENV['DB_PORT'],
	'database' => $_ENV['DB_NAME'],
	'username' => $_ENV['DB_USER'],
	'password' => $_ENV['DB_PASS'],
]);

$capsule->setAsGlobal();

$connection_resolver = $capsule->getDatabaseManager();

$migrator = new Migrator(
	new DatabaseMigrationRepository(
		$connection_resolver,
		'__migrations',
	),
	$connection_resolver,
	new Filesystem(),
);

if (!$migrator->repositoryExists()) {
	$migrator->getRepository()->createRepository();
}

$migrator->run(__DIR__ . '/migrations');
//$migrator->deleteRepository();
